# Examples for functions from utils.splitting.

In [1]:
import numpy as np

import tt

from qttpdesolver.utils.general import MODE_NP, MODE_TT
from qttpdesolver.utils.splitting import half_array, eo_sub_array, part_array

## Vectors and matrices for examples

The vectors and matrices are constructed here in numpy format and then are transformed to [quantized] tensor train format (the last ones are named according to mask *_tt).

In [2]:
d = 6
n = 2**d
tau = 1.E-8

x = 1.*np.arange(n)+1
print x

x_tt = tt.tensor(x.reshape([2]*d, order='F'), tau)

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.
  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.  29.  30.
  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.  43.  44.  45.
  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.  57.  58.  59.  60.
  61.  62.  63.  64.]


## Examples

In [3]:
help(half_array)
print half_array(x, 0)
print half_array(x_tt, 0, tau).full().flatten('F')

Help on function half_array in module qttpdesolver.utils.splitting:

half_array(x, ind, tau=None)
    Get a first (ind=0) or second (ind=1) half of array. In tt-case transform
    d-dim array A to (d-1)-dim array.
    ** For MODE_TT it is assumed that x is a QTT-tensor with standard
    mode size 2. If it's wrong, and mode size is n!=2, then for ind=0 function
    returns x[:len(x)/n] and so on.

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.
  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.  29.  30.
  31.  32.]
[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.
  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.  29.  30.
  31.  32.]


In [4]:
print half_array(x, 1, tau)
print half_array(x_tt, 1, tau).full().flatten('F')

[ 33.  34.  35.  36.  37.  38.  39.  40.  41.  42.  43.  44.  45.  46.  47.
  48.  49.  50.  51.  52.  53.  54.  55.  56.  57.  58.  59.  60.  61.  62.
  63.  64.]
[ 33.  34.  35.  36.  37.  38.  39.  40.  41.  42.  43.  44.  45.  46.  47.
  48.  49.  50.  51.  52.  53.  54.  55.  56.  57.  58.  59.  60.  61.  62.
  63.  64.]


In [5]:
help(eo_sub_array)
print eo_sub_array(x, ind=0)
print eo_sub_array(x_tt, ind=0, tau=tau).full().flatten('F')

Help on function eo_sub_array in module qttpdesolver.utils.splitting:

eo_sub_array(x, ind, tau=None)
    Get a subarray x[0::2] of even x elements (ind=0) or
                   x[1::2] of odd  x elements (ind=1).
    ** For MODE_TT it transforms d-dim array x to (d-1)-dim array.

[  1.   3.   5.   7.   9.  11.  13.  15.  17.  19.  21.  23.  25.  27.  29.
  31.  33.  35.  37.  39.  41.  43.  45.  47.  49.  51.  53.  55.  57.  59.
  61.  63.]
[  1.   3.   5.   7.   9.  11.  13.  15.  17.  19.  21.  23.  25.  27.  29.
  31.  33.  35.  37.  39.  41.  43.  45.  47.  49.  51.  53.  55.  57.  59.
  61.  63.]


In [6]:
print eo_sub_array(x, ind=1, tau=tau)
print eo_sub_array(x_tt, ind=1, tau=tau).full().flatten('F')

[  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.  22.  24.  26.  28.  30.
  32.  34.  36.  38.  40.  42.  44.  46.  48.  50.  52.  54.  56.  58.  60.
  62.  64.]
[  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.  22.  24.  26.  28.  30.
  32.  34.  36.  38.  40.  42.  44.  46.  48.  50.  52.  54.  56.  58.  60.
  62.  64.]


In [7]:
help(part_array)
for i in range(2**(d/2)):
    print part_array(x, i)
for i in range(2**(d/2)):
    print part_array(x_tt, i, tau).full().flatten('F')

Help on function part_array in module qttpdesolver.utils.splitting:

part_array(x, num, tau=None)
    For an array of length 2^(2d) get a part (num = 0, 1, ..., 2**d - 1) 
    of length 2^d.
    *** It works also for arrays of len 2^(2d+1) in that case
        part has len 2^(d+1) and num 0, 1, ..., 2**d - 1.

[ 1.  2.  3.  4.  5.  6.  7.  8.]
[  9.  10.  11.  12.  13.  14.  15.  16.]
[ 17.  18.  19.  20.  21.  22.  23.  24.]
[ 25.  26.  27.  28.  29.  30.  31.  32.]
[ 33.  34.  35.  36.  37.  38.  39.  40.]
[ 41.  42.  43.  44.  45.  46.  47.  48.]
[ 49.  50.  51.  52.  53.  54.  55.  56.]
[ 57.  58.  59.  60.  61.  62.  63.  64.]
[ 1.  2.  3.  4.  5.  6.  7.  8.]
[  9.  10.  11.  12.  13.  14.  15.  16.]
[ 17.  18.  19.  20.  21.  22.  23.  24.]
[ 25.  26.  27.  28.  29.  30.  31.  32.]
[ 33.  34.  35.  36.  37.  38.  39.  40.]
[ 41.  42.  43.  44.  45.  46.  47.  48.]
[ 49.  50.  51.  52.  53.  54.  55.  56.]
[ 57.  58.  59.  60.  61.  62.  63.  64.]


In [8]:
# numpy version is not correct for part_array for the case d%2 = 1 but tt one works correct!
d = 5
n = 2**d
tau = 1.E-8

x = 1.*np.arange(n)+1
print x

x_tt = tt.tensor(x.reshape([2]*d, order='F'), tau)

for i in range(2**(d/2)):
    print part_array(x, i, tau)
for i in range(2**(d/2)):
    print part_array(x_tt, i, tau).full().flatten('F')

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.
  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.  29.  30.
  31.  32.]
[ 1.  2.  3.  4.  5.]
[  6.   7.   8.   9.  10.]
[ 11.  12.  13.  14.  15.]
[ 16.  17.  18.  19.  20.]
[ 1.  2.  3.  4.  5.  6.  7.  8.]
[  9.  10.  11.  12.  13.  14.  15.  16.]
[ 17.  18.  19.  20.  21.  22.  23.  24.]
[ 25.  26.  27.  28.  29.  30.  31.  32.]
