# Examples for functions from utils.transform2mesh module.

In [1]:
import numpy as np
from numpy.linalg import norm
import time

import tt

from qttpdesolver.utils.transform2mesh import transform2finer
from qttpdesolver.utils.transform2mesh import transform2coarser

# 1D case: finer

In [2]:
d = 3; n = 2**d; dim = 1; tau = 1.E-8
x = np.arange(n)+1.; x[0] = 5.; x[3] = 18.; x[7] = 100.
x_tt = tt.tensor(x.reshape([2]*(d*dim), order='F'), tau)

help(transform2finer)
print x
print transform2finer(x, 1, tau, reps=1)
print transform2finer(x_tt, 1, tau).full().flatten('F')

print transform2finer(x, 1, reps=2)

Help on function transform2finer in module qttpdesolver.utils.transform2mesh:

transform2finer(x, dim, tau=None, reps=1)
    Transform a given vector x of size N=2^{d*dim}, that is assumed to be
    defined on appropriate spatial grid, to a finer grid with
    N1=2^{(d+1)*dim} nodes. The transformation is repeated reps-times.

[   5.    2.    3.   18.    5.    6.    7.  100.]
[   2.5    5.     3.5    2.     2.5    3.    10.5   18.    11.5    5.
    5.5    6.     6.5    7.    53.5  100. ]
[  2.5   5.    3.5   2.    2.5   3.   10.5  18.   11.5   5.    5.5   6.
   6.5   7.   53.5 100. ]
[   1.25    2.5     3.75    5.      4.25    3.5     2.75    2.      2.25
    2.5     2.75    3.      6.75   10.5    14.25   18.     14.75   11.5
    8.25    5.      5.25    5.5     5.75    6.      6.25    6.5     6.75
    7.     30.25   53.5    76.75  100.  ]


In [3]:
d = 30; n = 2**d; dim = 1; tau = 1.E-8

x_tt = tt.xfun(2, d)

_t = time.time()
res = transform2finer(x_tt, dim, tau)
print 'Total time for d=%-2d: %-8.4f'%(d, time.time()-_t)

Total time for d=30: 0.0163  


# 1D case: coarser

In [4]:
d = 4; n = 2**d; dim = 1; tau = 1.E-8
x = np.arange(n)+1.; x[0] = 5.; x[3] = 18.; x[7] = 100.
x_tt = tt.tensor(x.reshape([2]*(d*dim), order='F'), tau)

help(transform2coarser)
print x
print transform2coarser(x, 1, tau, reps=1)
print transform2coarser(x_tt, 1, tau).full().flatten('F')

print transform2coarser(x, 1, reps=2)

Help on function transform2coarser in module qttpdesolver.utils.transform2mesh:

transform2coarser(x, dim, tau=None, reps=1)
    Transform a given vector x of size N=2^{d*dim}, that is assumed to be
    defined on appropriate spatial grid, to a coarser grid with
    N1=2^{(d-1)*dim} nodes. The transformation is repeated reps-times.

[   5.    2.    3.   18.    5.    6.    7.  100.    9.   10.   11.   12.
   13.   14.   15.   16.]
[   2.   18.    6.  100.   10.   12.   14.   16.]
[   2.   18.    6.  100.   10.   12.   14.   16.]
[  18.  100.   12.   16.]


In [5]:
d = 30; n = 2**d; dim = 1; tau = 1.E-8

x_tt = tt.xfun(2, d)

_t = time.time()
res = transform2coarser(x_tt, dim, tau)
print 'Total time for d=%-2d: %-8.4f'%(d, time.time()-_t)

Total time for d=30: 0.0020  


# 2D case: finer

In [9]:
d = 2; n = 2**d; dim = 2; tau = 1.E-8
x = np.arange(n*n)+1.; x[0] = 5.; x[3] = 18.; x[7] = 100.
x_tt = tt.tensor(x.reshape([2]*(d*dim), order='F'), tau)

help(transform2finer)
print x
print transform2finer(x, 2, reps=1)

print x.reshape((n, n), order='F').T[::-1, :]
print transform2finer(x, 2, tau, reps=1).reshape((2*n, 2*n), order='F').T[::-1, :]
print transform2finer(x_tt, 2, tau).full().flatten('F').reshape((2*n, 2*n), order='F').T[::-1, :]

print transform2finer(x, 2, reps=2).reshape((4*n, 4*n), order='F').T[::-1, :]

Help on function transform2finer in module qttpdesolver.utils.transform2mesh:

transform2finer(x, dim, tau=None, reps=1)
    Transform a given vector x of size N=2^{d*dim}, that is assumed to be
    defined on appropriate spatial grid, to a finer grid with
    N1=2^{(d+1)*dim} nodes. The transformation is repeated reps-times.

[   5.    2.    3.   18.    5.    6.    7.  100.    9.   10.   11.   12.
   13.   14.   15.   16.]
[   1.25    2.5     1.75    1.      1.25    1.5     5.25    9.      2.5
    5.      3.5     2.      2.5     3.     10.5    18.      2.5     5.
    4.5     4.      4.5     5.     32.     59.      2.5     5.      5.5
    6.      6.5     7.     53.5   100.      3.5     7.      7.5     8.
    8.5     9.     32.5    56.      4.5     9.      9.5    10.     10.5
   11.     11.5    12.      5.5    11.     11.5    12.     12.5    13.
   13.5    14.      6.5    13.     13.5    14.     14.5    15.     15.5
   16.  ]
[[  13.   14.   15.   16.]
 [   9.   10.   11.   12.]
 [   5.

In [10]:
d = 30; n = 2**d; dim = 2; tau = 1.E-8

x_tt = tt.xfun(2, 2*d)

_t = time.time()
res = transform2finer(x_tt, dim, tau)
print 'Total time for d=%-2d: %-8.4f'%(d, time.time()-_t)

Total time for d=30: 0.0326  


# 2D case: coarser

In [14]:
d = 3; n = 2**d; dim = 2; tau = 1.E-8
x = np.arange(n*n)+1.; x[0] = 5.; x[3] = 18.; x[7] = 100.
x_tt = tt.tensor(x.reshape([2]*(d*dim), order='F'), tau)

help(transform2coarser)
print x.reshape((n, n), order='F').T[::-1, :]
print transform2coarser(x, 2, tau, reps=1).reshape((n/2, n/2), order='F').T[::-1, :]
print transform2coarser(x_tt, 2, tau).full().flatten('F').reshape((n/2, n/2), order='F').T[::-1, :]

print transform2coarser(x, 2, reps=2).reshape((n/4, n/4), order='F').T[::-1, :]

print transform2coarser(x, 2, reps=3).reshape((n/8, n/8), order='F').T[::-1, :]

Help on function transform2coarser in module qttpdesolver.utils.transform2mesh:

transform2coarser(x, dim, tau=None, reps=1)
    Transform a given vector x of size N=2^{d*dim}, that is assumed to be
    defined on appropriate spatial grid, to a coarser grid with
    N1=2^{(d-1)*dim} nodes. The transformation is repeated reps-times.

[[  57.   58.   59.   60.   61.   62.   63.   64.]
 [  49.   50.   51.   52.   53.   54.   55.   56.]
 [  41.   42.   43.   44.   45.   46.   47.   48.]
 [  33.   34.   35.   36.   37.   38.   39.   40.]
 [  25.   26.   27.   28.   29.   30.   31.   32.]
 [  17.   18.   19.   20.   21.   22.   23.   24.]
 [   9.   10.   11.   12.   13.   14.   15.   16.]
 [   5.    2.    3.   18.    5.    6.    7.  100.]]
[[ 58.  60.  62.  64.]
 [ 42.  44.  46.  48.]
 [ 26.  28.  30.  32.]
 [ 10.  12.  14.  16.]]
[[ 58.  60.  62.  64.]
 [ 42.  44.  46.  48.]
 [ 26.  28.  30.  32.]
 [ 10.  12.  14.  16.]]
[[ 60.  64.]
 [ 28.  32.]]
[[ 64.]]


In [15]:
d = 30; n = 2**d; dim = 2; tau = 1.E-8

x_tt = tt.xfun(2, 2*d)

_t = time.time()
res = transform2coarser(x_tt, dim, tau)
print 'Total time for d=%-2d: %-8.4f'%(d, time.time()-_t)

Total time for d=30: 0.0028  


# Composition:

In [16]:
d = 3; n = 2**d; dim = 2; tau = 1.E-8
x = np.arange(n*n)+1.; x[0] = 5.; x[3] = 18.; x[7] = 100.

print x.reshape((n, n), order='F').T[::-1, :]
xc = transform2coarser(x, 2, tau, reps=1)
print xc.reshape((n/2, n/2), order='F').T[::-1, :]
xf = transform2finer(xc, 2, tau, reps=1)
print xf.reshape((n, n), order='F').T[::-1, :]

[[  57.   58.   59.   60.   61.   62.   63.   64.]
 [  49.   50.   51.   52.   53.   54.   55.   56.]
 [  41.   42.   43.   44.   45.   46.   47.   48.]
 [  33.   34.   35.   36.   37.   38.   39.   40.]
 [  25.   26.   27.   28.   29.   30.   31.   32.]
 [  17.   18.   19.   20.   21.   22.   23.   24.]
 [   9.   10.   11.   12.   13.   14.   15.   16.]
 [   5.    2.    3.   18.    5.    6.    7.  100.]]
[[ 58.  60.  62.  64.]
 [ 42.  44.  46.  48.]
 [ 26.  28.  30.  32.]
 [ 10.  12.  14.  16.]]
[[ 29.   58.   59.   60.   61.   62.   63.   64. ]
 [ 25.   50.   51.   52.   53.   54.   55.   56. ]
 [ 21.   42.   43.   44.   45.   46.   47.   48. ]
 [ 17.   34.   35.   36.   37.   38.   39.   40. ]
 [ 13.   26.   27.   28.   29.   30.   31.   32. ]
 [  9.   18.   19.   20.   21.   22.   23.   24. ]
 [  5.   10.   11.   12.   13.   14.   15.   16. ]
 [  2.5   5.    5.5   6.    6.5   7.    7.5   8. ]]
