# Examples for functions from utils.grid module.

In [1]:
import numpy as np

import tt

from qttpdesolver.utils.general import MODE_NP, MODE_TT
from qttpdesolver.utils.grid import quan_on_grid, coord2ind, delta_on_grid, deltas_on_grid

## Vectors and matrices for examples

The vectors and matrices are constructed here in numpy format and then are transformed to [quantized] tensor train format (the last ones are named according to mask *_tt).

In [2]:
d = 4
n = 2**d
h = 1./n
tau = 1.E-8
eps = 1.E-8

def func_1d(x):
    return x*x+1./(x+2.)

def func_1d_tt(x):
    return x*x+1./(x+2.)

def func_2d(x, y):
    return x*y*y+y/(x+2.)

def func_2d_tt(r):
    x, y = r[:, 0], r[:, 1]
    return x*y*y+y/(x+2.)

def func_3d(x, y, z):
    return x*y*z*z+z/(x+y+2.)

def func_3d_tt(r):
    x, y, z = r[:, 0], r[:, 1], r[:, 2]
    return x*y*z*z+z/(x+y+2.)

## Examples 1D

In [3]:
f1 = quan_on_grid(func_1d, d, 1, tau, eps, MODE_NP, 
                  grid='cell centers', name='F', verb=False)
f1_tt = quan_on_grid(func_1d_tt, d, 1, tau, eps, MODE_TT, 
                     grid='cc', name='F', verb=True)
print f1[1], f1_tt.full().flatten('F')[1], func_1d(3.*h/2.)

f1 = quan_on_grid(func_1d, d, 1, tau, eps, MODE_NP, 
                  grid='left corners', name='F', verb=False)
f1_tt = quan_on_grid(func_1d_tt, d, 1, tau, eps, MODE_TT, 
                     grid='lc', name='F', verb=True)
print f1[1], f1_tt.full().flatten('F')[1], func_1d(h)

f1 = quan_on_grid(func_1d, d, 1, tau, eps, MODE_NP, 
                  grid='right corners', name='F', verb=False)
f1_tt = quan_on_grid(func_1d_tt, d, 1, tau, eps, MODE_TT, 
                     grid='rc', name='F', verb=True)
print f1[1], f1_tt.full().flatten('F')[1], func_1d(2*h)

f1 = quan_on_grid(func_1d, d, 1, tau, eps, MODE_NP, 
                  grid='upper-x edge midpoints', name='F', verb=False)
f1_tt = quan_on_grid(func_1d_tt, d, 1, tau, eps, MODE_TT, 
                     grid='uxe', name='F', verb=True)
# Is the same as 'cell centers' for 1D case.
print f1[1], f1_tt.full().flatten('F')[1], func_1d(3.*h/2.)

  Construction of F
=multifuncrs= sweep 1{2}, max_dy: 3.343e-01, erank: 2.64575
=multifuncrs= sweep 2{1}, max_dy: 4.546e-16, erank: 2.64575
0.486401002799 0.486401002799 0.486401002799
  Construction of F
=multifuncrs= sweep 1{2}, max_dy: 3.753e-01, erank: 2.64575
=multifuncrs= sweep 2{1}, max_dy: 2.622e-15, erank: 2.64575
0.488754734848 0.488754734848 0.488754734848
  Construction of F
=multifuncrs= sweep 1{2}, max_dy: 3.134e-01, erank: 2.64575
=multifuncrs= sweep 2{1}, max_dy: 7.918e-16, erank: 2.64575
0.486213235294 0.486213235294 0.486213235294
  Construction of F
=multifuncrs= sweep 1{2}, max_dy: 3.343e-01, erank: 2.64575
=multifuncrs= sweep 2{1}, max_dy: 4.546e-16, erank: 2.64575
0.486401002799 0.486401002799 0.486401002799


In [4]:
f1 = quan_on_grid(func_1d, d, 1, tau, eps, MODE_NP, 
                  grid='upper-x edge midpoints', name='F', verb=False, inv=True)
f1_tt = quan_on_grid(func_1d_tt, d, 1, tau, eps, MODE_TT, 
                     grid='uxe', name='F', verb=True, inv=True)
# Is the same as 'cell centers' for 1D case.
print f1[1], f1_tt.full().flatten('F')[1], 1./func_1d(3.*h/2.)

  Construction of F
=multifuncrs= sweep 1{2}, max_dy: 7.879e-01, erank: 2.64575
=multifuncrs= sweep 2{1}, max_dy: 6.619e-15, erank: 2.64575
2.055916814 2.055916814 2.055916814


## Examples 2D

In [5]:
f1 = quan_on_grid(func_2d, d, 2, tau, eps, MODE_NP, 
                  grid='cell centers', name='F', verb=False)
f1_tt = quan_on_grid(func_2d_tt, d, 2, tau, eps, MODE_TT, 
                     grid='cc', name='F', verb=True)
print f1[1], f1_tt.full().flatten('F')[1], func_2d(3.*h/2., h/2.)

f1 = quan_on_grid(func_2d, d, 2, tau, eps, MODE_NP, 
                  grid='left corners', name='F', verb=False)
f1_tt = quan_on_grid(func_2d_tt, d, 2, tau, eps, MODE_TT, 
                     grid='lc', name='F', verb=True)
print f1[1], f1_tt.full().flatten('F')[1], func_2d(h, 0.)

f1 = quan_on_grid(func_2d, d, 2, tau, eps, MODE_NP, 
                  grid='right corners', name='F', verb=False)
f1_tt = quan_on_grid(func_2d_tt, d, 2, tau, eps, MODE_TT, 
                     grid='rc', name='F', verb=True)
print f1[1], f1_tt.full().flatten('F')[1], func_2d(2*h, h)

f1 = quan_on_grid(func_2d, d, 2, tau, eps, MODE_NP, 
                  grid='upper-x edge midpoints', name='F', verb=False)
f1_tt = quan_on_grid(func_2d_tt, d, 2, tau, eps, MODE_TT, 
                     grid='uxe', name='F', verb=True)
print f1[1], f1_tt.full().flatten('F')[1], func_2d(3.*h/2., h)

f1 = quan_on_grid(func_2d, d, 2, tau, eps, MODE_NP, 
                  grid='upper-y edge midpoints', name='F', verb=False)
f1_tt = quan_on_grid(func_2d_tt, d, 2, tau, eps, MODE_TT, 
                     grid='uye', name='F', verb=True)
print f1[1], f1_tt.full().flatten('F')[1], func_2d(2.*h, h/2.)

  Construction of F
=multifuncrs= sweep 1{2}, max_dy: 2.404e+00, erank: 4.69042
=multifuncrs= sweep 2{1}, max_dy: 7.474e-16, erank: 5.47723
0.0150169258687 0.0150169258687 0.0150169258687
  Construction of F
=multifuncrs= sweep 1{2}, max_dy: 2.665e+00, erank: 4.69042
=multifuncrs= sweep 2{1}, max_dy: 8.902e-16, erank: 5.47723
0.0 -1.17961196366e-16 0.0
  Construction of F
=multifuncrs= sweep 1{2}, max_dy: 2.169e+00, erank: 4.69042
=multifuncrs= sweep 2{1}, max_dy: 8.690e-16, erank: 5.47723
0.0299000459559 0.0299000459559 0.0299000459559
  Construction of F
=multifuncrs= sweep 1{2}, max_dy: 2.126e+00, erank: 4.69042
=multifuncrs= sweep 2{1}, max_dy: 6.515e-16, erank: 5.47723
0.0302169572062 0.0302169572062 0.0302169572062
  Construction of F
=multifuncrs= sweep 1{2}, max_dy: 2.453e+00, erank: 4.69042
=multifuncrs= sweep 2{1}, max_dy: 1.007e-15, erank: 5.47723
0.0148279526654 0.0148279526654 0.0148279526654


## Examples 3D

In [6]:
f1 = quan_on_grid(func_3d, d, 3, tau, eps, MODE_NP, 
                  grid='cell centers', name='F', verb=False)
f1_tt = quan_on_grid(func_3d_tt, d, 3, tau, eps, MODE_TT, 
                     grid='cc', name='F', verb=True)
print f1[1], f1_tt.full().flatten('F')[1], func_3d(3.*h/2., h/2., h/2.)

f1 = quan_on_grid(func_3d, d, 3, tau, eps, MODE_NP, 
                  grid='left corners', name='F', verb=False)
f1_tt = quan_on_grid(func_3d_tt, d, 3, tau, eps, MODE_TT, 
                     grid='lc', name='F', verb=True)
print f1[1], f1_tt.full().flatten('F')[1], func_3d(h, 0., 0.)

f1 = quan_on_grid(func_3d, d, 3, tau, eps, MODE_NP, 
                  grid='right corners', name='F', verb=False)
f1_tt = quan_on_grid(func_2d_tt, d, 2, tau, eps, MODE_TT, 
                     grid='rc', name='F', verb=True)
print f1[1], f1_tt.full().flatten('F')[1], func_3d(2*h, h, h)

f1 = quan_on_grid(func_3d, d, 3, tau, eps, MODE_NP, 
                  grid='upper-x edge midpoints', name='F', verb=False)
f1_tt = quan_on_grid(func_3d_tt, d, 3, tau, eps, MODE_TT, 
                     grid='uxe', name='F', verb=True)
print f1[1], f1_tt.full().flatten('F')[1], func_3d(3.*h/2., h, h)

f1 = quan_on_grid(func_3d, d, 3, tau, eps, MODE_NP, 
                  grid='upper-y edge midpoints', name='F', verb=False)
f1_tt = quan_on_grid(func_3d_tt, d, 3, tau, eps, MODE_TT, 
                     grid='uye', name='F', verb=True)
print f1[1], f1_tt.full().flatten('F')[1], func_3d(2.*h, h/2., h)

f1 = quan_on_grid(func_3d, d, 3, tau, eps, MODE_NP, 
                  grid='upper-z edge midpoints', name='F', verb=False)
f1_tt = quan_on_grid(func_3d_tt, d, 3, tau, eps, MODE_TT, 
                     grid='uze', name='F', verb=True)
print f1[1], f1_tt.full().flatten('F')[1], func_3d(2.*h, h, h/2.)

  Construction of F
=multifuncrs= sweep 1{2}, max_dy: 6.657e+00, erank: 5.19615
=multifuncrs= sweep 2{1}, max_dy: 1.089e-06, erank: 7.34847
=multifuncrs= sweep 2{2}, max_dy: 1.089e-06, erank: 7.61577
=multifuncrs= sweep 3{1}, max_dy: 2.107e-09, erank: 7.34847
0.0147087433759 0.0147087434099 0.0147087433759
  Construction of F
=multifuncrs= sweep 1{2}, max_dy: 2.163e+00, erank: 5.19615
=multifuncrs= sweep 2{1}, max_dy: 4.554e-08, erank: 7.34847
=multifuncrs= sweep 2{2}, max_dy: 4.554e-08, erank: 7.61577
=multifuncrs= sweep 3{1}, max_dy: 2.688e-09, erank: 7.34847
0.0 -2.77555756156e-17 0.0
  Construction of F
=multifuncrs= sweep 1{2}, max_dy: 2.169e+00, erank: 4.69042
=multifuncrs= sweep 2{1}, max_dy: 6.115e-16, erank: 5.47723
0.0286019461496 0.0299000459559 0.0286019461496
  Construction of F
=multifuncrs= sweep 1{2}, max_dy: 5.916e+00, erank: 5.19615
=multifuncrs= sweep 2{1}, max_dy: 5.644e-09, erank: 7.34847
0.02900839543 0.0290083954918 0.02900839543
  Construction of F
=multifuncrs=

In [2]:
# 1D coord2ind
L = 2.
d = 3
n = 2**d
h = L/n

ind_exp = [0, 0, 0, 0, 1, 1, n-2, n-1, n-1]
gx = h*(np.arange(n)+1.)
for r in [[-1.], [0.], [h], [h*1.4], [h*1.51], [h*1.99], [h*n-h*0.6], [h*n-h*0.1], [h*n+10]]:
    ind = coord2ind(r, d, L)
    print gx, r, ind

[ 0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ] [-1.0] 0
[ 0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ] [0.0] 0
[ 0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ] [0.25] 0
[ 0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ] [0.35] 0
[ 0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ] [0.3775] 1
[ 0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ] [0.4975] 1
[ 0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ] [1.85] 6
[ 0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ] [1.975] 7
[ 0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ] [12.0] 7


In [3]:
# 2D coord2ind
L = 2.
d = 3
n = 2**d
h = L/n

ind_exp = [0, 0, 0, 0, 9, 9, 54, 63, 63]
gx = h*(np.arange(n)+1.)
for r in [[-1., -1.], [0., 0.], [h, h], [h*1.4, h*1.4], [h*1.51, h*1.51], 
          [h*1.99, h*1.99], [h*n-h*0.6, h*n-h*0.6], [h*n-h*0.1, h*n-h*0.1], [h*n+10, h*n+10]]:
    ind = coord2ind(r, d, L)
    print gx, r, ind

[ 0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ] [-1.0, -1.0] 0
[ 0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ] [0.0, 0.0] 0
[ 0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ] [0.25, 0.25] 0
[ 0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ] [0.35, 0.35] 0
[ 0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ] [0.3775, 0.3775] 9
[ 0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ] [0.4975, 0.4975] 9
[ 0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ] [1.85, 1.85] 54
[ 0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ] [1.975, 1.975] 63
[ 0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ] [12.0, 12.0] 63


In [4]:
# 3D coord2ind
L = 2.
d = 2
n = 2**d
h = L/n

ind_exp = [0, 0, 0, 0, 21, 21, 42, 63, 63]
gx = h*(np.arange(n)+1.)
for r in [[-1.]*3, [0.]*3, [h]*3, [h*1.4]*3, [h*1.51]*3, 
          [h*1.99]*3, [h*n-h*0.6]*3, [h*n-h*0.1]*3, [h*n+10]*3]:
    ind = coord2ind(r, d, L)
    print gx, r, ind

[ 0.5  1.   1.5  2. ] [-1.0, -1.0, -1.0] 0
[ 0.5  1.   1.5  2. ] [0.0, 0.0, 0.0] 0
[ 0.5  1.   1.5  2. ] [0.5, 0.5, 0.5] 0
[ 0.5  1.   1.5  2. ] [0.7, 0.7, 0.7] 0
[ 0.5  1.   1.5  2. ] [0.755, 0.755, 0.755] 21
[ 0.5  1.   1.5  2. ] [0.995, 0.995, 0.995] 21
[ 0.5  1.   1.5  2. ] [1.7, 1.7, 1.7] 42
[ 0.5  1.   1.5  2. ] [1.95, 1.95, 1.95] 63
[ 0.5  1.   1.5  2. ] [12.0, 12.0, 12.0] 63


In [2]:
L = 1.
d = 3
n = 2**d
h = L/n
r, val = [2*h+0.45*h], 3.
print delta_on_grid(r, val, d, tau=1.E-8, mode=MODE_NP), val/h
print delta_on_grid(r, val, d, tau=1.E-8, mode=MODE_TT).full().flatten('F')
r, val = [2*h+0.51*h], 2.
print delta_on_grid(r, val, d, tau=1.E-8, mode=MODE_NP), val/h
print delta_on_grid(r, val, d, tau=1.E-8, mode=MODE_TT).full().flatten('F')
r, val = [2*h+0.51*h, 2*h+0.51*h], 2.
print delta_on_grid(r, val, d, tau=1.E-8, mode=MODE_NP), val/h/h
print delta_on_grid(r, val, d, tau=1.E-8, mode=MODE_TT).full().flatten('F')

[  0.  24.   0.   0.   0.   0.   0.   0.] 24.0
[  0.  24.   0.   0.   0.   0.   0.   0.]
[  0.   0.  16.   0.   0.   0.   0.   0.] 16.0
[  0.   0.  16.   0.   0.   0.   0.   0.]
[   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
    0.    0.    0.    0.    0.    0.  128.    0.    0.    0.    0.    0.
    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
    0.    0.    0.    0.] 128.0
[   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
    0.    0.    0.    0.    0.    0.  128.    0.    0.    0.    0.    0.
    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
    0.    0.    0.    0.]


In [4]:
L = 1.
d = 3
n = 2**d
h = L/n
r_list = [[2*h+0.45*h], [3*h+0.45*h]]
val_list = [3., 2.]
print deltas_on_grid(r_list, val_list, d, tau=1.E-8, mode=MODE_NP)

[  0.  24.  16.   0.   0.   0.   0.   0.]
