# Examples for functions from utils.spec_matr.

In [1]:
import numpy as np

import tt

from qttpdesolver.utils.general import MODE_NP, MODE_TT, MODE_SP
from qttpdesolver.utils.spec_matr import toeplitz, eye, volterra, findif, shift, interpol_1d, vzeros_except_one

In [2]:
help(toeplitz)

c = np.arange(4)+1
r =-np.arange(4)*2
print c, r
print toeplitz(c, r)

Help on CPUOverloaded in module qttpdesolver.utils.spec_matr:

toeplitz(...)
    Toepllitz matrix with c is the first column and
    r[1:] is the first row (except the first element).

[1 2 3 4] [ 0 -2 -4 -6]
[[ 1. -2. -4. -6.]
 [ 2.  1. -2. -4.]
 [ 3.  2.  1. -2.]
 [ 4.  3.  2.  1.]]


In [7]:
help(eye)

print eye(2, 4, mode=MODE_NP)
print eye(2, 4, mode=MODE_SP).toarray()
print eye(2, 4, mode=MODE_TT).full()

Help on function eye in module qttpdesolver.utils.spec_matr:

eye(d, n, mode=0)
    Eye matrix: diag(1, 1,..., 1).

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [3]:
help(volterra)

print volterra(2, 4, 1., mode=MODE_NP)
print volterra(2, 4, 1., 1.E-8, mode=MODE_TT).full()

Help on function volterra in module qttpdesolver.utils.spec_matr:

volterra(d, n, h, tau=None, mode=0)
    Volterra integral 1D matrix
    [i, j] = h if i>=j and = 0 otherwise.

[[ 1.  0.  0.  0.]
 [ 1.  1.  0.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  1.]]
[[  1.00000000e+00  -5.55111512e-17   0.00000000e+00   0.00000000e+00]
 [  1.00000000e+00   1.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.00000000e+00   1.00000000e+00   1.00000000e+00   2.22044605e-16]
 [  1.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00]]


In [4]:
help(findif)

print findif(2, 4, 1., mode=MODE_NP)
print findif(2, 4, 1., mode=MODE_SP).toarray()
print findif(2, 4, 1., 1.E-8, mode=MODE_TT).full()

Help on function findif in module qttpdesolver.utils.spec_matr:

findif(d, n, h, tau=None, mode=0)
    Finite difference 1D matrix
    [i, j] = 1/h if i=j, [i, j] =-1/h if i=j+1 and = 0 otherwise.

[[ 1.  0.  0.  0.]
 [-1.  1.  0.  0.]
 [ 0. -1.  1.  0.]
 [ 0.  0. -1.  1.]]
[[ 1.  0.  0.  0.]
 [-1.  1.  0.  0.]
 [ 0. -1.  1.  0.]
 [ 0.  0. -1.  1.]]
[[ 1.  0.  0.  0.]
 [-1.  1.  0.  0.]
 [ 0. -1.  1.  0.]
 [ 0.  0. -1.  1.]]


In [5]:
help(shift)

print shift(2, 4, mode=MODE_NP)
print shift(2, 4, tau=1.E-8, mode=MODE_SP).toarray()
print shift(2, 4, tau=1.E-8, mode=MODE_TT).full()

Help on function shift in module qttpdesolver.utils.spec_matr:

shift(d, n, tau=None, mode=0)
    Shift 1D matrix
    [i, j] = 1 if i=j+1, [i, j] = 0 otherwise.

[[ 0.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]]
[[ 0.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]]
[[  1.45918397e-15   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.00000000e+00   1.01509476e-15   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.00000000e+00   1.45918397e-15   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   1.01509476e-15]]


In [6]:
help(interpol_1d)

print interpol_1d(2, 4, mode=MODE_NP)
print interpol_1d(2, 4, 1.E-8, mode=MODE_TT).full()

Help on function interpol_1d in module qttpdesolver.utils.spec_matr:

interpol_1d(d, n, tau=None, mode=0)
    1D interpolation matrix.
    Is valid only for mesh x_j = h+hj, j=0,1,...,n-1.

[[ 0.5  0.   0.   0.   0.   0.   0.   0. ]
 [ 1.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.5  0.   0.5  0.   0.   0.   0.   0. ]
 [ 0.   0.   1.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.5  0.   0.5  0.   0.   0. ]
 [ 0.   0.   0.   0.   1.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.5  0.   0.5  0. ]
 [ 0.   0.   0.   0.   0.   0.   1.   0. ]]
[[  5.00000000e-01   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  5.00000000e-01   0.00000000e+00   5.00000000e-01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  3.92523115e-17   0.00000000e+00   1.00

# OLD CODE BELOW!

In [10]:
help(eye_first)
print eye_first(2, 4, MODE_NP, use_csr=False)

res1 = eye_first(10, 2**10, MODE_NP)
res2 = eye_first(10, 2**10, MODE_TT).full()

assert norm(res1 - res2)/norm(res1) < 1.E-16

Help on function eye_first in module utils.spec_matr:

eye_first(d, n, mode=0, use_csr=False)
    Diagonal matrix: diag(1, 0,..., 0, 0).

[[1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [11]:
help(eye_last)
print eye_last(2, 4, MODE_NP, use_csr=False)

res1 = eye_last(10, 2**10, MODE_NP)
res2 = eye_last(10, 2**10, MODE_TT).full()

assert norm(res1 - res2)/norm(res1) < 1.E-16

Help on function eye_last in module utils.spec_matr:

eye_last(d, n, mode=0, use_csr=False)
    Diagonal matrix: diag(0, 0,..., 0, 1).

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]]


In [12]:
help(eye_except_first)
print eye_except_first(2, 4, MODE_NP, use_csr=False)

res1 = eye_except_first(10, 2**10, MODE_NP)
res2 = eye_except_first(10, 2**10, MODE_TT).full()

assert norm(res1 - res2)/norm(res1) < 1.E-16

Help on function eye_except_first in module utils.spec_matr:

eye_except_first(d, n, mode=0, use_csr=False)
    Diagonal matrix: diag(0, 1,..., 1, 1).

[[ 0.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [13]:
help(eye_except_last)
print eye_except_last(2, 4, MODE_NP, use_csr=False)

res1 = eye_except_last(10, 2**10, MODE_NP)
res2 = eye_except_last(10, 2**10, MODE_TT).full()

assert norm(res1 - res2)/norm(res1) < 1.E-16

Help on function eye_except_last in module utils.spec_matr:

eye_except_last(d, n, mode=0, use_csr=False)
    Diagonal matrix: diag(0, 1,..., 1, 1).

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  0.]]


In [14]:
help(eye_p1_first)
print eye_p1_first(2, 4, MODE_NP, use_csr=False)

res1 = eye_p1_first(10, 2**10, MODE_NP)
res2 = eye_p1_first(10, 2**10, MODE_TT).full()

assert norm(res1 - res2)/norm(res1) < 1.E-15

Help on function eye_p1_first in module utils.spec_matr:

eye_p1_first(d, n, mode=0, use_csr=False)
    Matrix: A[i, j] = 0, A[0, 1] = 1.

[[0 1 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [15]:
help(eye_p1_last)
print eye_p1_last(2, 4, MODE_NP, use_csr=False)

res1 = eye_p1_last(10, 2**10, MODE_NP)
res2 = eye_p1_last(10, 2**10, MODE_TT).full()

assert norm(res1 - res2)/norm(res1) < 1.E-15

Help on function eye_p1_last in module utils.spec_matr:

eye_p1_last(d, n, mode=0, use_csr=False)
    Matrix: A[i, j] = 0, A[-1, -2] = 1.

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 0 0 0]]


In [17]:
help(ones_first)
print ones_first(2, 4, MODE_NP)

res1 = ones_first(10, 2**10, MODE_NP)
res2 = ones_first(10, 2**10, MODE_TT).full().flatten('F')

assert norm(res1 - res2)/norm(res1) < 1.E-15

Help on function ones_first in module utils.spec_matr:

ones_first(d, n, mode=0, use_csr=False)
    Vector: [1, 0,..., 0, 0] (shape=(n, ) or qtt-tensor)

[ 1.  0.  0.  0.]


In [18]:
help(ones_last)
print ones_last(2, 4, MODE_NP)

res1 = ones_last(10, 2**10, MODE_NP)
res2 = ones_last(10, 2**10, MODE_TT).full().flatten('F')

assert norm(res1 - res2)/norm(res1) < 1.E-15

Help on function ones_last in module utils.spec_matr:

ones_last(d, n, mode=0)
    Vector: [0, 0,..., 0, 1] (shape=(n, ) or qtt-tensor)

[ 0.  0.  0.  1.]


In [19]:
help(ones_except_first)
print ones_except_first(2, 4, MODE_NP)

res1 = ones_except_first(10, 2**10, MODE_NP)
res2 = ones_except_first(10, 2**10, MODE_TT).full().flatten('F')

assert norm(res1 - res2)/norm(res1) < 1.E-15

Help on function ones_except_first in module utils.spec_matr:

ones_except_first(d, n, mode=0)
    Vector: [0, 1,..., 1, 1] (shape=(n, ) or qtt-tensor)

[ 0.  1.  1.  1.]


In [20]:
help(ones_except_last)
print ones_except_last(2, 4, MODE_NP)

res1 = ones_except_last(10, 2**10, MODE_NP)
res2 = ones_except_last(10, 2**10, MODE_TT).full().flatten('F')

assert norm(res1 - res2)/norm(res1) < 1.E-15

Help on function ones_except_last in module utils.spec_matr:

ones_except_last(d, n, mode=0)
    Vector: [1, 1,..., 1, 0] (shape=(n, ) or qtt-tensor)

[ 1.  1.  1.  0.]


In [6]:
help(zeros_except_one)

print zeros_except_one(2, 2**2, 2, 1, MODE_NP, value=2.)

res1 = zeros_except_one(10, 2**10, 4, 5, MODE_NP, value=1.)
res2 = zeros_except_one(10, 2**10, 4, 5, MODE_TT, value=1.).full()#.flatten('F')

assert norm(res1 - res2)/norm(res1) < 1.E-15

Help on function zeros_except_one in module utils.spec_matr:

zeros_except_one(d, n, i, j=None, mode=0, value=1.0)
    Construct a vector (if j is None) or matrix (if is not None)
    with only one nonzero element in position [i, j] with given value.

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  0.  0.]]


In [8]:
help(zeros_except_one)

print zeros_except_one(2, 2**2, 2, None, MODE_NP, value=2.)

res1 = zeros_except_one(10, 2**10, 4, None, MODE_NP, value=1.)
res2 = zeros_except_one(10, 2**10, 4, None, MODE_TT, value=1.).full().flatten('F')

assert norm(res1 - res2)/norm(res1) < 1.E-15

Help on function zeros_except_one in module utils.spec_matr:

zeros_except_one(d, n, i, j=None, mode=0, value=1.0)
    Construct a vector (if j is None) or matrix (if is not None)
    with only one nonzero element in position [i, j] with given value.

[ 0.  0.  1.  0.]


$$
B = h
\begin{bmatrix}
    1 &  &  &  \\
    1 & 1 &  & \\
	\vdots &    &\ddots  & \\
  	1 &  \dots &\dots	& 1 
\end{bmatrix}, \;\;
$$

Let introduce Volterra matrix $B^{n \times n}$, vector $w_i^{n \times 1}$, $q_i^{n \times 1}$ and a vector of ones $e^{n \times 1}$:
$$
B = h
\begin{bmatrix}
    1 &  &  &  \\
    1 & 1 &  & \\
	\vdots &    &\ddots  & \\
  	1 &  \dots &\dots	& 1 
\end{bmatrix}, \;\;
w_i [k] = \begin{cases}
0, \;\; k != i, \\
1, \;\; k = i
\end{cases}, \;\;
q_i [k] = \begin{cases}
0, \;\; k < i, \\
1, \;\; k \geq i
\end{cases}
$$

then we have:
$$
B w_i = q_i, \;\; B^T w_i = 
$$

Sherman-Morrison formula:
$$
(S+uv^T)^{-1} = S^{-1} - \frac{S^{-1} u v^T S^{-1}}{1 + v^T S^{-1} u}.
$$

Let $S^{n \times n}=B^{-1} B^{-T}$, $u v^T = k_i w_i w_i^T$ where $k_i$ is a constant, then:
$$
(B^{-1} B^{-T} + k_i w_i w_i^T)^{-1} =
B^T B - k_i \frac{B^T B w_i w_i^T B^T B}{1 + k_i w_i^T B^T B w_i} = 
B^T B - k_i \frac{B^T (B w_i) (B w_i)^T B}{1 + k_i (B w_i)^T (B w_i)} = 
B^T B - k_i \frac{B^T q_i q_i^T B}{1 + k_i q_i^T q_i} = 
B^T B - \frac{B^T q_i q_i^T B}{1/k_i  + (n-i)}.
$$

And then:
$$
(B^{-1} B^{-T} + k_i w_i w_i^T+ k_j w_j w_j^T)^{-1} =
B^T B - \frac{B^T q_i q_i^T B}{1/k_i  + (n-i)} - 
k_j \frac{B^T B w_j w_j^T B^T B - \frac{B^T q_i q_i^T B}{1/k_i  + (n-i)} w_j w_j^T B^T B - \frac{B^T q_i q_i^T B}{1/k_i  + (n-i)}}{1 + k_j w_j^T B^T B - \frac{B^T q_i q_i^T B}{1/k_i  + (n-i)} w_j}
$$

In [98]:
d = 2
n = 2**d
B = m_volterra(d, n, 1., mode=MODE_NP)
iB = m_findif(d, n, 1., mode=MODE_NP)

i = 2
ki = 222.
wi = np.zeros((n, 1)); wi[i, 0] = 1.
qi = np.zeros((n, 1))
for k in range(i, n):
    qi[k, 0] = 1.
    
X = iB.dot(iB.T) + ki*wi.dot(wi.T)
X = np.linalg.inv(X)

Y = B.T.dot(B) - B.T.dot(qi).dot(qi.T).dot(B)/(1./ki+(n-i))

print np.linalg.norm(X-Y)/np.linalg.norm(X)

2.80822622271e-16


In [103]:
print iB.T.dot(iB) #!!!

[[ 2. -1.  0.  0.]
 [-1.  2. -1.  0.]
 [ 0. -1.  2. -1.]
 [ 0.  0. -1.  1.]]


In [94]:
d = 2
n = 2**d
B = m_volterra(d, n, 1., mode=MODE_NP)
print B

i = 3
j = 2
wi = np.zeros((n, 1))
wi[i, 0] = 1.
wj = np.zeros((n, 1))
wj[j, 0] = 1.
qi = np.zeros((n, 1))
for k in range(i, n):
    qi[k, 0] = 1.
qj = np.zeros((n, 1))
for k in range(j, n):
    qj[k, 0] = 1.

print wi.dot(wj.T)

[[ 1.  0.  0.  0.]
 [ 1.  1.  0.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  1.]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  1.  0.]]


In [2]:
help(vzeros_except_one)

d = 3
n = 2**d
value = 2.

print vzeros_except_one(d, ind=0, mode=MODE_NP, value=value)
print vzeros_except_one(d, ind=2, mode=MODE_NP, value=value)
print vzeros_except_one(d, ind=2, mode=MODE_TT, value=value).full().flatten('F')
print vzeros_except_one(d, ind=n-1, mode=MODE_NP, value=value)

Help on function vzeros_except_one in module qttpdesolver.utils.spec_matr:

vzeros_except_one(d, ind, mode=0, value=1.0)
    Construct a vector in the given mode of length 2**d with only one
    nonzero element in position ind, that is equal to a given value.

[ 2.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  2.  0.  0.  0.  0.  0.]
[ 0.  0.  2.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  2.]
