# Advanced API for qttpdesolver package.

We consider various examples of qttpdesolver usage (see api_basic_1d.ipynb, api_basic_2d.ipynb and api_basic_3d.ipynb first).

In [1]:
%matplotlib inline
import numpy as np

from qttpdesolver import Pde, create_solver, auto_solve
from qttpdesolver import MODE_NP, MODE_TT, MODE_SP, SOLVER_FS, SOLVER_FD

### 1D Solvers and modes comparison:

we solve 1D stationary diffusion PDE with known analytical solution with different combinations of solvers and modes.

In [2]:
PDE = Pde()
PDE.set_model('Simple. Analyt 1D diffusion PDE')
PDE.set_params([np.pi*2])
     
PDE.set_tau(tau=1.E-14, eps_lss=1.E-14, tau_lss=1.E-14)
PDE.set_lss_params(nswp=20, kickrank=4, local_prec='n', local_iters=2,
                   local_restart=20, trunc_norm=1, max_full_size=100)
PDE.set_verb(False, False, False)

d_list = {}
d_list[SOLVER_FS] = {MODE_NP: range(8, 13, 2),
                     MODE_TT: range(8, 23, 2)}
d_list[SOLVER_FD] = {MODE_NP: range(8, 11, 2),
                     MODE_TT: range(8, 21, 2),
                     MODE_SP: range(8, 21, 2)}
for mode in [MODE_TT, MODE_SP, MODE_NP]:
    for solver in [SOLVER_FS, SOLVER_FD]:
        if solver==SOLVER_FS and mode==MODE_SP:
            continue
        print '------ <  MODE: %s  >  <  Solver: %s  >'%(mode, solver)
        for d in d_list[solver][mode]:
            PDE.set_solver_txt(solver) 
            PDE.set_mode(mode) 
            PDE.update_d(d)
            PDESolver = auto_solve(PDE, return_solver=True)  

------ <  MODE: tt  >  <  Solver: fs  >
d= 8|fs-tt|er=5.1e-05 |erdx=2.6e-05 |T=   0.071|R=   4.3
d=10|fs-tt|er=3.2e-06 |erdx=1.6e-06 |T=   0.044|R=   3.9
d=12|fs-tt|er=2.0e-07 |erdx=1.0e-07 |T=   0.091|R=   3.6
d=14|fs-tt|er=1.3e-08 |erdx=6.3e-09 |T=   0.062|R=   3.0
d=16|fs-tt|er=7.8e-10 |erdx=4.0e-10 |T=   0.068|R=   2.7
d=18|fs-tt|er=4.9e-11 |erdx=2.5e-11 |T=   0.077|R=   2.4
d=20|fs-tt|er=3.1e-12 |erdx=1.5e-12 |T=   0.100|R=   2.2
d=22|fs-tt|er=1.9e-13 |erdx=9.3e-14 |T=   0.094|R=   2.0
------ <  MODE: tt  >  <  Solver: fd  >
d= 8|fd-tt|er=5.1e-05 |erdx=2.6e-05 |T=   0.107|R=   4.8|It=20
d=10|fd-tt|er=3.2e-06 |erdx=1.6e-06 |T=   0.161|R=   4.6|It=20
d=12|fd-tt|er=2.0e-07 |erdx=1.3e-06 |T=   0.248|R=   4.4|It=20
d=14|fd-tt|er=5.9e-08 |erdx=2.0e-06 |T=   0.456|R=   5.2|It=20
d=16|fd-tt|er=4.2e-07 |erdx=9.0e-04 |T=   0.703|R=   8.1|It=20
d=18|fd-tt|er=3.1e-06 |erdx=9.8e-02 |T=   1.691|R=   9.8|It=20
d=20|fd-tt|er=3.9e-06 |erdx=7.6e-02 |T=   1.752|R=  14.2|It=20
------ <  MODE: sp  >  

### 2D Solvers and modes comparison:

we solve 2D stationary diffusion PDE with known analytical solution with different combinations of solvers and modes.

In [2]:
PDE = Pde()
PDE.set_model('Simple. Analyt 2D diffusion PDE')
PDE.set_params([np.pi, np.pi*2])
     
PDE.set_tau(tau=1.E-10, eps_lss=1.E-10, tau_lss=1.E-10)
PDE.set_lss_params(nswp=20, kickrank=4, local_prec='n', local_iters=2,
                   local_restart=20, trunc_norm=1, max_full_size=100)
PDE.set_verb(False, False, False)

d_list = {}
d_list[SOLVER_FS] = {MODE_NP: range(3,  6, 1),
                     MODE_TT: range(3, 15, 1)}
d_list[SOLVER_FD] = {MODE_NP: range(3,  6, 1),
                     MODE_TT: range(3, 13, 1),
                     MODE_SP: range(3, 10, 1)}
for mode in [MODE_TT, MODE_SP, MODE_NP]:
    for solver in [SOLVER_FS, SOLVER_FD]:
        if solver==SOLVER_FS and mode==MODE_SP:
            continue
        print '------ <  MODE: %s  >  <  Solver: %s  >'%(mode, solver)
        for d in d_list[solver][mode]:
            PDE.set_solver_txt(solver) 
            PDE.set_mode(mode) 
            PDE.update_d(d)
            PDESolver = auto_solve(PDE, return_solver=True)     

------ <  MODE: tt  >  <  Solver: fs  >
d= 3|fs-tt|er=4.4e-02 |erdx=3.2e-02 |erdy=1.8e-02 |T=   0.128|R=   4.1|It= 2
d= 4|fs-tt|er=1.1e-02 |erdx=7.9e-03 |erdy=4.5e-03 |T=   0.174|R=   5.6|It= 3
d= 5|fs-tt|er=2.7e-03 |erdx=2.0e-03 |erdy=1.1e-03 |T=   0.281|R=   6.5|It= 3
d= 6|fs-tt|er=6.8e-04 |erdx=4.9e-04 |erdy=2.8e-04 |T=   0.458|R=   6.9|It= 3
d= 7|fs-tt|er=1.7e-04 |erdx=1.2e-04 |erdy=7.0e-05 |T=   0.781|R=   7.1|It= 4
d= 8|fs-tt|er=4.2e-05 |erdx=3.1e-05 |erdy=1.8e-05 |T=   1.029|R=   7.0|It= 3
d= 9|fs-tt|er=1.1e-05 |erdx=7.7e-06 |erdy=4.4e-06 |T=   1.333|R=   7.2|It= 3
d=10|fs-tt|er=2.6e-06 |erdx=1.9e-06 |erdy=1.1e-06 |T=   1.776|R=   7.1|It= 3
d=11|fs-tt|er=6.6e-07 |erdx=4.8e-07 |erdy=2.8e-07 |T=   2.091|R=   6.6|It= 3
d=12|fs-tt|er=1.7e-07 |erdx=1.2e-07 |erdy=6.9e-08 |T=   1.951|R=   7.4|It= 3
d=13|fs-tt|er=4.1e-08 |erdx=3.0e-08 |erdy=1.7e-08 |T=   1.940|R=   7.3|It= 3
d=14|fs-tt|er=1.0e-08 |erdx=8.5e-09 |erdy=5.3e-09 |T=   2.184|R=   7.7|It= 3
------ <  MODE: tt  >  <  Solver: fd

### 3D Solvers and modes comparison:

we solve 3D stationary diffusion PDE with known analytical solution with different combinations of solvers and modes.

# Note, solvers for 3D case are under development now !!

In [2]:
PDE = Pde()
PDE.set_model('Simple. Analyt 3D diffusion PDE')
PDE.set_params([np.pi, np.pi*2, np.pi*3])
     
PDE.set_tau(tau=1.E-6, eps_lss=1.E-6, tau_lss=1.E-6)
PDE.set_lss_params(nswp=20, kickrank=4, local_prec='n', local_iters=2,
                   local_restart=20, trunc_norm=1, max_full_size=100)
PDE.set_verb(False, False, False)

d_list = {}
d_list[SOLVER_FS] = {MODE_NP: range(3,  4, 1),
                     MODE_TT: range(3,  7, 1)}
d_list[SOLVER_FD] = {MODE_NP: range(3,  4, 1),
                     MODE_TT: range(3,  8, 1),
                     MODE_SP: range(3,  4, 1)}
for mode in [MODE_TT, MODE_SP, MODE_NP]:
    for solver in [SOLVER_FS, SOLVER_FD]:
        if solver==SOLVER_FS and mode==MODE_SP:
            continue
        print '------ <  MODE: %s  >  <  Solver: %s  >'%(mode, solver)
        for d in d_list[solver][mode]:
            PDE.set_solver_txt(solver) 
            PDE.set_mode(mode) 
            PDE.update_d(d)
            PDESolver = auto_solve(PDE, return_solver=True)

------ <  MODE: tt  >  <  Solver: fs  >
d= 3|fs-tt|er=1.1e-01 |erdx=8.6e-02 |erdy=5.3e-02 |erdz=4.7e-02 |T=   0.399|R=   6.6|It= 4
d= 4|fs-tt|er=2.6e-02 |erdx=2.1e-02 |erdy=1.4e-02 |erdz=1.2e-02 |T=   0.691|R=   9.2|It= 5
d= 5|fs-tt|er=6.5e-03 |erdx=5.2e-03 |erdy=3.5e-03 |erdz=3.1e-03 |T=   1.740|R=  11.6|It= 5
d= 6|fs-tt|er=1.6e-03 |erdx=1.3e-03 |erdy=8.8e-04 |erdz=7.8e-04 |T=   2.935|R=  13.9|It= 6
------ <  MODE: tt  >  <  Solver: fd  >
d= 3|fd-tt|er=1.1e-01 |erdx=8.6e-02 |erdy=5.3e-02 |erdz=4.7e-02 |T=   0.306|R=   6.6|It= 3
d= 4|fd-tt|er=2.6e-02 |erdx=2.1e-02 |erdy=1.4e-02 |erdz=1.2e-02 |T=   0.174|R=   7.8|It= 4
d= 5|fd-tt|er=6.5e-03 |erdx=5.2e-03 |erdy=3.5e-03 |erdz=3.1e-03 |T=   0.245|R=   7.6|It= 4
d= 6|fd-tt|er=1.6e-03 |erdx=1.3e-03 |erdy=8.8e-04 |erdz=7.8e-04 |T=   0.447|R=   7.0|It= 4
d= 7|fd-tt|er=4.1e-04 |erdx=3.3e-04 |erdy=2.2e-04 |erdz=2.0e-04 |T=   0.411|R=   6.3|It= 4
------ <  MODE: sp  >  <  Solver: fd  >
d= 3|fd-sp|er=1.1e-01 |erdx=8.6e-02 |erdy=5.3e-02 |erdz=4.7e-

In [2]:
PDE = Pde()
PDE.set_model('Simple. Analyt 3D diffusion PDE')
PDE.set_params([np.pi, np.pi*2, np.pi*3])
     
PDE.set_tau(tau=1.E-10, eps_lss=1.E-10, tau_lss=1.E-10)
PDE.set_lss_params(nswp=20, kickrank=4, local_prec='n', local_iters=2,
                   local_restart=20, trunc_norm=1, max_full_size=100)
PDE.set_verb(False, False, False)
PDE.update_d(3)

PDE.set_solver_txt(SOLVER_FS) 
PDE.set_mode(MODE_NP) 
FS = auto_solve(PDE, return_solver=True)    
PDE.set_solver_txt(SOLVER_FD) 
PDE.set_mode(MODE_NP) 
FD = auto_solve(PDE, return_solver=True)     

(64,)
(64,)
(64,)
8 3
(512, 512)
(512, 512)
(512, 512)
d= 3|fs-np|er=1.1e-01 |erdx=8.6e-02 |erdy=5.3e-02 |erdz=4.7e-02 |T=   0.826
d= 3|fd-np|er=1.1e-01 |erdx=8.6e-02 |erdy=5.3e-02 |erdz=4.7e-02 |T=   0.130


In [3]:
from qttpdesolver import Vector, Matrix
I = Matrix.eye(PDE.d, PDE.mode, PDE.tau)
Z = Matrix.unit(PDE.d, PDE.mode, PDE.tau, -1, -1)
J = I - Z

Ax = FD.Sx.dot(FD.iBx.T).dot(FD.Kx).dot(FD.iBx).dot(FD.Sx) + FD.Zx
X1 = Ax.dot(FS.Hx)
print (I.kron(I).kron(J)).rel_err(X1)

Ay = FD.Sy.dot(FD.iBy.T).dot(FD.Ky).dot(FD.iBy).dot(FD.Sy) + FD.Zy
X1 = Ay.dot(FS.Hy)
print (I.kron(J).kron(I)).rel_err(X1)

Az = FD.Sz.dot(FD.iBz.T).dot(FD.Kz).dot(FD.iBz).dot(FD.Sz) + FD.Zz
X1 = Az.dot(FS.Hz)
print (J.kron(I).kron(I)).rel_err(X1)

6.70073221165e-16
7.23840011256e-16
7.6732291436e-16


In [4]:
FS.Wx.x

NameError: name 'FS' is not defined

In [15]:
print np.linalg.norm(FS.A.x[:PDE.n**3, :PDE.n**3] - FS.Hx.x-FS.Hz.x)
print np.linalg.norm(FS.A.x[PDE.n**3:, :PDE.n**3] -FS.Hz.x)
print np.linalg.norm(FS.A.x[:PDE.n**3, PDE.n**3:] -FS.Hz.x)
print np.linalg.norm(FS.A.x[PDE.n**3:, PDE.n**3:] - FS.Hy.x-FS.Hz.x)
print np.linalg.norm(FS.rhs.x[PDE.n**3:] - FS.Hz.dot(FS.f).x)
print np.linalg.norm(FS.rhs.x[:PDE.n**3] - FS.Hz.dot(FS.f).x)

1.31147605429
0.810978545591
0.0
4.3080906683e-17
0.0
0.0


In [38]:
def _n2d(n):
    d = int(np.log2(n))
    if 2**d != n:
        raise ValueError('Incorrect size.')
    return d

def block(mlist, name='df'):
    '''
    Construct square block matrix from list of lists, that contains matrices
    of equal shape and maybe some (not all!) None/int/float entries.
    For None/int/float entries elements in the corresponding block
    will be filled by zeros.
    '''
    res = None
    if not isinstance(mlist, list):
        raise ValueError('This should be a list.')
    d0 = _n2d(len(mlist)) 
    n0 = 2**d0
    for i, mrow in enumerate(mlist):
        print i
        if not isinstance(mrow, list):
            raise ValueError('List of lists should contain only lists.')
        if not n0 == len(mrow):
            raise ValueError('The length of the list and sub-lists should be equal.')  
        for j, m in enumerate(mrow):
            print j
            if (m is None or isinstance(m, (int, float))) or \
               (isinstance(m, Matrix) and m.isnone):
                print 'heh'
                continue
            e = Matrix.unit(d0, m.mode, m.tau, i, j)
            if res is None:
                res = e.kron(m)
            else:
                res+= e.kron(m)
        print e.x
        print m.x
        print res.x
        print
    res.name = name
    return res
    
a = np.array([[1., 2.], [3., 4.]])
b = np.array([[11., 12.], [13., 14.]])
c = np.array([[31., 32.], [33., 34.]])
d = np.array([[41., 42.], [43., 44.]])
x = block([[Matrix(b), Matrix(b)], [Matrix(c), Matrix(d)]])
print x.to_np

0
0
1
[[ 0.  1.]
 [ 0.  0.]]
[[ 11.  12.]
 [ 13.  14.]]
[[ 11.  12.  11.  12.]
 [ 13.  14.  13.  14.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]]

1
0
1
[[ 0.  0.]
 [ 0.  1.]]
[[ 41.  42.]
 [ 43.  44.]]
[[ 11.  12.  11.  12.]
 [ 13.  14.  13.  14.]
 [ 31.  32.  41.  42.]
 [ 33.  34.  43.  44.]]

[[ 11.  12.  11.  12.]
 [ 13.  14.  13.  14.]
 [ 31.  32.  41.  42.]
 [ 33.  34.  43.  44.]]


In [23]:
print Matrix.unit(2, MODE_NP, 1.E-8, 1, 2).to_np

[[ 0.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [3]:
PDE = Pde()
PDE.set_model('Simple. Analyt 3D diffusion PDE')
PDE.set_params([np.pi, np.pi*2, np.pi*3])
     
PDE.set_tau(tau=1.E-10, eps_lss=1.E-10, tau_lss=1.E-10)
PDE.set_lss_params(nswp=20, kickrank=4, local_prec='n', local_iters=2,
                   local_restart=20, trunc_norm=1, max_full_size=100)
PDE.set_verb(False, False, False)

d_list = {}
d_list[SOLVER_FS] = {MODE_NP: range(3,  4, 1),
                     MODE_TT: range(3,  8, 1)}
d_list[SOLVER_FD] = {MODE_NP: range(3,  4, 1),
                     MODE_TT: range(3,  8, 1),
                     MODE_SP: range(3,  4, 1)}
for mode in [MODE_TT, MODE_SP, MODE_NP]:
    for solver in [SOLVER_FD]: # SOLVER_FS is not ready now
        if solver==SOLVER_FS and mode==MODE_SP:
            continue
        print '------ <  MODE: %s  >  <  Solver: %s  >'%(mode, solver)
        for d in d_list[solver][mode]:
            PDE.set_solver_txt(solver) 
            PDE.set_mode(mode) 
            PDE.update_d(d)
            PDESolver = auto_solve(PDE, return_solver=True)     

------ <  MODE: tt  >  <  Solver: fd  >
d= 3|fd-tt|er=1.1e-01 |erdx=8.6e-02 |erdy=5.3e-02 |erdz=4.7e-02 |T=   0.139|R=   8.0|It= 4
d= 4|fd-tt|er=2.6e-02 |erdx=2.1e-02 |erdy=1.4e-02 |erdz=1.2e-02 |T=   0.229|R=  13.6|It= 7
d= 5|fd-tt|er=6.5e-03 |erdx=5.2e-03 |erdy=3.5e-03 |erdz=3.1e-03 |T=   0.370|R=  16.3|It= 8
d= 6|fd-tt|er=1.6e-03 |erdx=1.3e-03 |erdy=8.8e-04 |erdz=7.8e-04 |T=   0.577|R=  17.2|It= 8
d= 7|fd-tt|er=4.1e-04 |erdx=3.3e-04 |erdy=2.2e-04 |erdz=2.0e-04 |T=   0.834|R=  15.8|It= 9
------ <  MODE: sp  >  <  Solver: fd  >
d= 3|fd-sp|er=1.1e-01 |erdx=8.6e-02 |erdy=5.3e-02 |erdz=4.7e-02 |T=   0.014
------ <  MODE: np  >  <  Solver: fd  >
d= 3|fd-np|er=1.1e-01 |erdx=8.6e-02 |erdy=5.3e-02 |erdz=4.7e-02 |T=   0.122
